### ISSUE TITLE
Default link style makes identifying links within text difficult

### ISSUE THREAD

**Issue by michaelck** [DH-Box/dhbox#114]
While looking through the "About" page I noticed that the styling for links causes some difficulty in identifying the difference between a link and regular text.

The contrast ratio between the link color (#2e1a57) and the text color (#333333) is extremely low: 1.19:1
[WebAIM Contrast Checker](http://webaim.org/resources/contrastchecker/)

A quick solution would be to alter the style in dhbox.css to include underlining of links:

```
a {
    color: #2e1a57;
    text-decoration: underline;
}
```

(P.S. Thanks for building this tool! I currently work at a Swarthmore College and hope to make use of it.)

**Comment by smythp** [comment]
Good catch. Contrast is important for accessibility!

Also, feel free to create a pull request with your proposed changes. Then if we integrate your update you'll be properly credited.

**Comment by michaelck** [comment]
Hi @smythp I have a version of main.less ready to propose as a pull request however when my bower dependencies install, Bootstrap v3.3.5 is installed. It looks like the project currently uses 3.3.0 which may account for some of the additional differences I see when comparing the dist/ results of my gulp build.

Would anyone mind offering advice on how I should proceed? If anyone knows how to force bower to install v3.3.0 that would be helpful too.

Thanks!

**Comment by szweibel** [comment]
I've added Bootstrap 3.3.5 as a dependency in the Bower file, so we'll go with that version.
