### ISSUE TITLE
Typo in README.md. Incorrect path to install_dhbox.sh

### ISSUE THREAD

**Issue by michaelck** [DH-Box/dhbox#118]
I noticed that the path to the install_dhbox.sh was incorrect. Submitted PR to correct the typo.

**Comment by szweibel** [comment]
Thanks!

**Comment by michaelck** [comment]
No problem, @szweibel! I'd love to keep pitching in from time to time if that's okay with you and your team. 

Do you have a Slack channel or Gitter for the project?

**Comment by smythp** [comment]
Stephen, any interest in an IRC channel for DH Box?

**Comment by szweibel** [comment]
Sure. I like the idea of using Slack as well. I haven't set up such a community before. Any thoughts?

**Comment by smythp** [comment]
I prefer IRC because I have open source leanings but can be 
persuaded into Slack if you think it will have more traction. For 
IRC you would create a room on Freenode and stick a bot in it to 
keep it open. For Slack I think you create a team and invite 
people/create some kind of open link.
