### ISSUE TITLE
Disk space full

### ISSUE THREAD

**Issue by smythp** [DH-Box/dhbox#136]
Getting disk space full messages and 100% usage in df -hl when creating two demonstration boxes.

**Comment by smythp** [comment]
Are people signing up? Why is disk space full now?

**Comment by szweibel** [comment]
I'm not seeing this, I just successfully created a demo box.

**Comment by smythp** [comment]
Just logged in and usage is at 96% now. Created a second demo box and usage
was 97%. Looks like this would cap the number of boxes we could run.

**Comment by szweibel** [comment]
Dang, I see it now. I'll create a new EC2 instance tomorrow with a bigger HD.

**Comment by szweibel** [comment]
new instance created with 30 GB HD
