### ISSUE TITLE
Wordpress container not restarting

### ISSUE THREAD

**Issue by smythp** [DH-Box/dhbox#138]

**Comment by smythp** [comment]
Restarts when I change restart policy to "always" with --restart flag. Unfortunately no support for this flag in dockerpy (boo, Dockerpy). Created issues there and in the tutum image repo and will look into fixing the non-zero exit status or whatever that causes this.

**Comment by szweibel** [comment]
I may have fixed it, by adding "restart_policy"
c.start(wp_container,
                publish_all_ports=True, restart_policy=restart_policy)

**Comment by smythp** [comment]
Did you use this for the policy?

{ "MaximumRetryCount": 0, "Name": "always" }

Test your solution and we can close this one out.

**Comment by szweibel** [comment]
I used
restart_policy = {"MaximumRetryCount": 10, "Name": "always"}
Yep, works.

**Comment by smythp** [comment]
Sweet
