### ISSUE TITLE
Add Stanford NLP services (NER specifically)

### ISSUE THREAD

**Issue by muziejus** [DH-Box/dhbox#143]
It'd be nice if the DHBox came w/ a CoreNLP installation that can then be referenced by (at least) the Python notebook / console.

This would necessitate:

* Upgrading the Java version to 1.8 (from 1.7)
* Pushing the 536Mb worth of CoreNLP JARs.

The latter I'm pretty sure I could do on my own w/ my students. The former I'm not as confident about.

Thanks.

**Comment by muziejus** [comment]
This works to upgrade the java, fwiw, so I guess I'm confident about that now (and could turn this into a .sh I upload)

```
# from: http://stackoverflow.com/questions/30177455/moving-from-jdk-1-7-to-jdk-1-8-on-ubuntu
# Newer versions of java *are* available

wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jdk-8u71-linux-x64.tar.gz
mkdir /opt/jdk
tar -zxf jdk-8u71-linux-x64.tar.gz -C /opt/jdk/
rm jdk-8u71-linux-x64.tar.gz
update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_71/bin/java 1
update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_71/bin/javac 1
update-alternatives --config java
update-alternatives --config javac
java -version
javac -version

**Comment by muziejus** [comment]
And to get Stanford NER running:

```
wget www-nlp.stanford.edu/software/stanford-ner-2015-12-09.zip
unzip stanford*
rm *.zip
mv stanford* ner # to save on typing
```
I got it up and running after fiddling w/ Python a bit more (the tokenizers had to be downloaded, for example).

**Comment by smythp** [comment]
Glad you got this running. We may upgrade Java in the near future once we make sure the new version doesn't cause trouble with MALLET. Let us know if you run into more issues and we can revisit this.

**Comment by muziejus** [comment]
Yeah, this is what I've set up so far:

https://gist.github.com/muziejus/bf0222ff5ac1a24bbee5e5eac9622c00

(for getting everything up and running in general) and then:

```
import nltk
from nltk.tag import StanfordNERTagger
tagger = StanfordNERTagger('/home/stanford-ner/classifiers/english.all.3class.distsim.crf.ser.gz', '/home/stanford-ner/stanford-ner.jar', encoding='utf-8')
```
as a separate module, `stanfordner.py` that gets uploaded and provides, for example, `stanfordner.tagger.tag(tokens)`.

**Comment by muziejus** [comment]
I understand it's ludicrous to hard-wire everything like this (and install stanford-ner in home?), but it works.

**Comment by smythp** [comment]
Looks like you have a workaround that's acceptable for the time being. Let us know if you run into anything you can't take care of on your end.

**Comment by muziejus** [comment]
Thanks. I'll roll w/ this for the time being and report back.
