### ISSUE TITLE
Rolling your own dhbox w/ AWS

### ISSUE THREAD

**Issue by muziejus** [DH-Box/dhbox#145]
Hello,

I've got an aws box up and running, with ports 80, 4000, and 5000 open. 

When I go to admin > apps > Jupyter notebooks (from another computer), I get `port 4000 website found` echoed to the console, but no notebooks appear. After a certain while, I get a timeout:

`The server at [my external IP] is taking too long to respond.`

I see that I have an IP address for eth0 and one for docker0, but neither is the same as the external IP shown above. Could this be the problem?

**Comment by szweibel** [comment]
It's possible you haven't opened the ports DH Box requires. Docker will run each app (Jupyter, R Studio, etc.) on a random port between 32768 and 61000.

**Comment by muziejus** [comment]
That's what I suspected. Thanks.
